### ISSUE TITLE
Error running 3D CT experiment

### ISSUE THREAD

**Issue by jiayangshi** [liyues/NeRP#3]
Hi, 

thank you for your great work! When I tried to run the 3D CT experiment using the command as given in readme `python train_ct_recon_3d.py --config configs/ct_recon_3d.yaml`, the following error showed up
```
ct_recon_3d/pancs_4dct_3d_real_phase6/img[40, 128, 128]_proj20_SIREN_512_256_8_L2_lr1e-05_encoder_gauss_scale4_size256
Load image: ./data/ct_data/pancs_4dct_phase6.npz
(40, 256, 256) 46 20
shape:torch.Size([40, 128, 128, 1]) | min:0.000 | max:1.000 | mean:0.105 | std:0.155
Traceback (most recent call last):
  File "train_ct_recon_3d.py", line 99, in <module>
    ct_projector = ConeBeam3DProjector(config['img_size'], config['proj_size'], config['num_proj'])
  File "/data/shij3/NeRP/ct_geometry_projector.py", line 140, in __init__
    self.forward_projector = Projection_ConeBeam(geo_param)
  File "/data/shij3/NeRP/ct_geometry_projector.py", line 87, in __init__
    reco_space, ray_trafo, FBPOper = build_conebeam_gemotry(self.param)
  File "/data/shij3/NeRP/ct_geometry_projector.py", line 69, in build_conebeam_gemotry
    impl='astra_cuda') # implementation back-end for the transform: ASTRA toolbox, using CUDA, 2D or 3D
TypeError: __init__() missing 1 required positional argument: 'vol_space'
```

**Comment by liyues** [comment]
Fixed the issue and the changes has been merged. Thanks.
